Use device-constants in Particle USB
particle-iot/particle-usb pull request #44
Opened 2021-11-05 22:04 UTC by monkbroc

Story details: https://app.shortcut.com/particle/story/89893

Pull in all the platform information needed to generate particle-usb classes from the device-constants package to make adding new platforms easier.

Additional changes:
- Drop support for Mesh commands
- Drop support for Core since it doesn't support USB vendor requests
- The `type` is now the same as the platform `name` to avoid having yet another identifier for the platform (Asset-Tracker becomes tracker)
- I removed the named classes `Photon`, `Electron`, etc from the package public interface because I couldn't find any use of those. Only `getDevices` and `openDeviceById` are the only package public interfaces uses that I can find in our code.

Open questions:
- Should we add a feature to device-constants called `usb-requests`? Or can we rely on the fact that if there are USB ids, we'll be supporting vendor request?
- Can we get rid of the `isPhoton`, `isElectron`, etc methods on the device class? I cannot find any hints that these are used.

2021-11-05 22:22 UTC, busticated commented on src/platforms.js
> +		productId: parseInt(productId.replace(/0x/, ''), 16)
i don't think you need the `.replace()` calls?

```js
parseInt('0x2b04', 16) // -> 11012
```

you could also do:

```js 
Number('0x2b04') // -> 11012 
```

...since JS includes special handling of string input ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#convert_numeric_strings_and_null_to_numbers))

2021-11-08 12:59 UTC, sergeuz requested changes
The PR looks good, I'm requesting changes mostly because of the removed `MeshDevice`'s `setSetupDone()` method that is still used in the CLI.

2021-11-08 12:59 UTC, sergeuz commented on src/device-base.js
> +	 * Platform ID.C
Typo.

2021-11-08 12:59 UTC, sergeuz commented on src/device-base.js
> +	 * TODO: (Julien) Are there any consumers using the isPhoton methods? Can this be simply removed?
Given that this is going to be a major library update anyway, let's go ahead and remove these methods :+1:

2021-11-08 12:59 UTC, sergeuz commented on src/mesh-device.js
> -	}
This method is used by the CLI's `usb setup-done` command.

2021-11-08 12:59 UTC, sergeuz commented on src/particle-usb.js
> +}, {});
:+1:

2021-11-08 12:59 UTC, sergeuz commented on src/platforms.js
> +});
This modifies the data that belongs to `@particle/device-constants` globally which may cause some hard to debug problems in the future.

2021-11-08 12:59 UTC, sergeuz commented on src/mesh-device.js
> -};
Let's also remove integration tests for mesh devices: https://github.com/particle-iot/particle-usb/blob/feature/sc-89893/particle-usb-supports-tron-platform/test/integration/mesh-device.js.

2021-11-08 16:34 UTC, monkbroc commented on src/mesh-device.js
> -	}
How about moving this to a Gen3Device class that could be mixed in based on the generation field?

2021-11-08 16:35 UTC, monkbroc commented
Thanks for the reviews. I'm not going to be able to prioritize this for a couple days, but at least it shows we're directionally aligned on how to add device-constants support to particle-usb.

2021-11-08 16:37 UTC, sergeuz commented on src/mesh-device.js
> -	}
Sounds good :+1:

2021-11-11 20:06 UTC, busticated commented on src/platforms.js
> +		productId: parseInt(productId.replace(/0x/, ''), 16)
✅ in https://github.com/particle-iot/particle-usb/pull/44/commits/d33ae8d6e5a9a690551639419e20066ba00ac26a

2021-11-11 20:07 UTC, busticated commented on src/device-base.js
> +	 * Platform ID.C
✅ in https://github.com/particle-iot/particle-usb/pull/44/commits/b8eefcf230ec78e2b7769f58a50b255fa730fc69

2021-11-11 20:07 UTC, busticated commented on src/device-base.js
> +	 * TODO: (Julien) Are there any consumers using the isPhoton methods? Can this be simply removed?
✅ in https://github.com/particle-iot/particle-usb/pull/44/commits/b8eefcf230ec78e2b7769f58a50b255fa730fc69

2021-11-11 20:07 UTC, busticated commented on src/platforms.js
> +});
✅ in https://github.com/particle-iot/particle-usb/pull/44/commits/d33ae8d6e5a9a690551639419e20066ba00ac26a

2021-11-11 20:08 UTC, busticated commented on src/mesh-device.js
> -};
✅ in https://github.com/particle-iot/particle-usb/pull/44/commits/c56325fc7c762e4042ea4da4ae830753325b81df

2021-11-12 13:44 UTC, sergeuz commented
Thanks for addressing the comments, @busticated. I added a mixin for Gen 3 devices as discussed with Julien. I'm going to merge this PR and test the library with the recent node-usb.

2021-11-12 13:44 UTC, sergeuz approved these changes

2021-11-12 13:45 UTC, merged