Sc 95109/enumerable ctrl request types
particle-iot/particle-usb pull request #56
Opened 2022-01-19 23:13 UTC by joegoggins

2022-01-21 14:17 UTC, sergeuz requested changes
Looks good apart from a minor bug that I noticed, thank you!

2022-01-21 14:17 UTC, sergeuz commented on src/device.js
> +			);
This will overwrite the existing object with the result code when the `dontThrow` option is used. Same for the other assignment below.

2022-01-21 14:25 UTC, joegoggins commented on src/device.js
> +			);
Right on @sergeuz , thanks for the review.

`dontThrow` is an undocumented, untested construct that only `enterListeningMode` uses. (and `sendRequest`, but we want to eliminate that anyway).

I feel like it'd be better to eliminate it and instead gracefully catch the error there. That approach work for you? If so, I'll add test coverage for `enterListeningMode` that ensures it works correctly when an error is thrown (and port  `enterListeningMode` to use sendProtobufRequest instead of sendRequest)

2022-01-21 14:31 UTC, sergeuz commented on src/device.js
> +			);
That would work too :+1:

2022-01-21 16:30 UTC, monkbroc approved these changes
The changes look great!

2022-01-21 16:30 UTC, monkbroc commented on test/support/fake-usb.js
> +	const opts = Object.assign({}, options, { type: deviceConstants.p2.name });
Little JS style thing: you can use the spread operator to combine objects more concisely than with `Object.assign`. No need to change it here, just sharing a trick.
```suggestion
	const opts = { ...options, type: deviceConstants.p2.name };
```

2022-01-22 00:38 UTC, joegoggins commented on src/device.js
> +			);
@sergeuz I eliminated `dontThrow` option in the last couple of commits. Also managed to get 100% test coverage over enterListeningMode + sendProtobufRequest and changed CI build to be `test:ci` which includes linter, tests, and code coverage minimums.

Hope this will work for ya, I'll check for your input first thing Monday and merge after if everything is cool and cut a 2.1.0 release

2022-01-24 18:23 UTC, merged