chore/sc-104328/dependencies
particle-iot/particle-usb pull request #66
Opened 2022-08-15 21:29 UTC by busticated

## Description

Updates dependencies, most notably major version bumps for `usb`, `@particle/device-constants`, and `webpack`.

## How to Test

1. Pull down this branch (`git pull && git checkout chore/sc-104328/dependencies`)
2. Reinstall dependencies (`npm run reinstall`)
3. Run tests (`npm run test:ci`)

**Outcome**

All tests pass both locally and in CI 👍 

## Related / Discussions

https://app.shortcut.com/particle/story/104328

2022-08-16 10:13 UTC, sergeuz requested changes

2022-08-16 10:13 UTC, sergeuz commented on package.json
> +    "protobufjs": "^6.11.3",
This module can't be a dev dependency as the generated protobuf file requires it.

2022-08-16 18:47 UTC, busticated commented on package.json
> +    "protobufjs": "^6.11.3",
ah, thank you 🙏 

i added a test to help catch this sort of thing going forward in https://github.com/particle-iot/particle-usb/pull/66/commits/54211e7fc44a727953263445c82f4f78598d7b12

...then fixed the issues in https://github.com/particle-iot/particle-usb/pull/66/commits/72aa1d861a6bedac6a124dca2ef5b6e69bd78319 https://github.com/particle-iot/particle-usb/pull/66/commits/86d89a9f1c79279138f403bf2565d025149552ea

2022-08-17 09:34 UTC, sergeuz commented on package.json
> +    "protobufjs": "^6.11.3",
Awesome, thanks!

2022-08-17 09:34 UTC, sergeuz approved these changes

2022-08-17 09:56 UTC, rickkas7 approved these changes
I was able to check out a fresh copy, npm install, and run test:ci woth no errors. Tested on Mac with node 12.

2022-08-17 15:53 UTC, merged