Feature/dfu impl
particle-iot/particle-usb pull request #89
Opened 2023-07-26 23:26 UTC by keeramis

## Description

This pull request introduces new functionality to enable firmware download to a module using the Device Firmware Update (DFU) mechanism. The `flashWithDfu` method is designed to enable the flashing of any USB device in DFU mode.

To utilize this functionality, users are required to provide the following required arguments: 
- the DFU interface number (which is obtained from device-constants). This change is later made in the CLI.
- binary content of the firmware which are parsed by the `binary-version-reader`
- the starting address at which the firmware should be downloaded
- and additional options specific to the download process such as `doManifestation : true` or `noErase : true`

## How to test

### Flash system parts and user parts

1. Checkout this branch
2. Point your test script to the folder path of this branch
```
const usb = require('/path/to/local/particle-usb');
const fs = require('fs-extra');
const { HalModuleParser } = require('binary-version-reader');

async function main() {
  const devices = await usb.getDevices();
  if (devices.length === 0) {
    throw new Error('No devices found');
  }
  const device = devices[0];
  console.log('Device : ', device);
  await device.open();
  await device.enterDfuMode();

  const buf = await fs.readFile('/path/to/binaries/5.4.0/p2/p2-system-part1@5.4.0.bin');
  const reader = new HalModuleParser();
  const parsed = await reader.parseBuffer({ fileBuffer: buf });
  const addr = parseInt(parsed.prefixInfo.moduleStartAddy, 16);
  await device.flashWithDfu(0, parsed.fileBuffer, addr, {}); // the `0` is obtained from particle-cli

  const bufTinker = await fs.readFile('/path/to/binaries/5.4.0/p2/p2-tinker@5.4.0.bin');
  const parsedTinker = await reader.parseBuffer({ fileBuffer: bufTinker });
  const addrTinker = parseInt(parsedTinker.prefixInfo.moduleStartAddy, 16);
  await device.flashWithDfu(0, parsedTinker.fileBuffer, addrTinker, { doManifestation: true });
}

main().catch((error) => {
  console.error('Error:', error.message);
});
```

### Flash DCT to flash device keys, for example
1. First obtain keys for the given device using `particle keys new deviceID`
2. The key is saved in a local folder. Use that folder path to read the data with binary encoding
```
const usb = require('/path/to/local/particle-usb');
const fs = require('fs-extra');
const { HalModuleParser } = require('binary-version-reader');

async function main() {
  const devices = await usb.getDevices();
  if (devices.length === 0) {
    throw new Error('No devices found');
  }
  const device = devices[0];
  console.log('Device : ', device);
  await device.open();
  await device.enterDfuMode();

  const keysBuf = await fs.readFile('/path/to/module/key', 'binary');
  await device.flashWithDfu(1, keysBuf, 3106, { doManifestation: true });
}

main().catch((error) => {
  console.error('Error:', error.message);
});
```

2023-07-27 09:50 UTC, keeramis commented
Just a quick update regarding the progress on the DFU upload functionality. I've encountered some challenges when implementing the upload feature on nodeusb perhaps/apparently due to differences in how webdfu and nodeusb handle the upload process. It might take some time to look at it so to avoid delaying the release of the current functionality, I'll proceed with creating this PR without the upload feature. Rest assured, I'll continue working on the upload functionality in a separate PR, but for the upcoming RC, it's not an essential requirement.

2023-07-27 09:59 UTC, keeramis commented on src/dfu-device.js
> +};
As I was working through the APIs and testing them out, I realized that all of the binary parsing can be done by the caller for a more cohesive workflow (the caller is particle-CLI in this case). This is because the CLI already has access to a variety of helper functions that can easily determine the the correct dfu interface by checking the device constants, calculating the start addresses, etc. By delegating the binary parsing to the CLI, we can avoid duplicating functionality in the particle-usb library.

2023-07-27 23:31 UTC, hugomontero commented
Tested with argon:
I'm getting an `sos` issue after flashing `system-part` and `user-part`
I'll try again tomorrow. I'm assuming my implementation is broken hehe

2023-07-27 23:37 UTC, hugomontero commented on src/dfu-device.js
> +};
One thing I faced:
Flashing argon-system-part1@4.1.0.bin at 196608 (1/2)
Error: device.flashWithDfu is not a function

If the device starts on `normal` mode then the first time it tries to do the flashWith... it won't work for some reason.
The device HAS to be opened once is in dfu mode and in that way it will work

2023-07-27 23:38 UTC, hugomontero approved these changes
It worked for me.
Just one little observation related when the device starts in `normal` mode instead of `dfu` mode

2023-07-28 00:48 UTC, monkbroc reviewed
Looks good. I'll continue to review the structure tomorrow.

2023-07-28 00:48 UTC, monkbroc commented on package.json
> +    "binary-version-reader": "^2.2.0",
I see you didn't end up using binary-version-reader in particle-usb so remove the dependency.

If we did need binary-version-reader, we'd want to add it as a peer dependency like device-constants so it's not necessary to update particle-usb when a new version is released. We'd rely on the application to have the latest version.

2023-07-28 00:48 UTC, monkbroc commented on src/LICENSE
> +Copyright (c) 2016, Devan Lai
Let's put the copyright notice for web-dfu in the files that are derived from that project.

2023-07-28 00:48 UTC, monkbroc commented on src/dfu-device.js
> +};
Hugo, this is on purpose: only the methods supported by the current device are available. If your device is not in DFU, you can't flash in DFU.

2023-07-28 00:48 UTC, monkbroc commented on src/dfu-device.js
> +			throw new Error(err);
This try/catch is redundant. If there's a chance that the 2 methods above throw something that's not an Error (like `throw 'Unknown error';`) then we need to fix those methods so they only throw errors.

2023-07-28 00:48 UTC, monkbroc commented on src/dfu.js
> +		// FIXME: _sendDnloadRequest changed
What does this FIXME mean?

2023-07-28 00:48 UTC, monkbroc commented on src/dfu.js
> +		await this.poll_until(
Does this have a timeout?

2023-07-28 00:48 UTC, monkbroc commented on src/set-device-prototype.js
> +	prototypes[platform.name] = klass;
Can you rename this to `classes` and the constant to `DEVICE_CLASSES`

2023-07-28 00:48 UTC, monkbroc commented on src/set-device-prototype.js
> +	const proto = DEVICE_PROTOTYPES[usbDevice.type];	// DEVICE_CLASSES.
Make this function consistent with the proto -> klass naming too.

2023-07-28 13:38 UTC, hugomontero commented on src/dfu-device.js
> +};
Oh what I mean is:
Having this code:

```
  // device in normal mode here
  await device.open();
  await device.enterDfuMode();
  await device.flashWithDfu(0, module.fileBuffer, addr, { doManifestation: true })
```

It fails with `flashWithDfu` is not a function even though the device is in dfu mode now
I have to "reopen" de device (once the device is in dfu ) in order to get the right function

2023-07-28 13:47 UTC, keeramis commented on src/dfu-device.js
> +};
Makes sense. I believe it's because of this logic here which inherits the Dfu() only during the open process. I believe that's why if we are directly calling the `flashWithDfu` it won't work?

https://github.com/particle-iot/particle-usb/blob/main/src/device-base.js#L147

2023-07-28 18:26 UTC, keeramis commented on test/support/fake-usb.js
> +		// }
I removed this because data is no longer empty for download requests (other than leave requests)

2023-08-01 11:58 UTC, sergeuz requested changes

2023-08-01 11:58 UTC, sergeuz commented on src/dfu.js
> +		if (bStatus < 0 || bStatus > 255 || !bState) {
`bStatus` can't be negative nor greater than 255 here.

2023-08-01 11:58 UTC, sergeuz commented on src/dfu.js
> +				if (triesLeft === 0 || error !== 'stall') {
This retry logic won't work as `_sendDnloadRequest` never throws strings such as `stall`.

2023-08-01 11:58 UTC, sergeuz commented on src/dfu.js
> +	_getFirstWritableSegment() {
Unused method. Same [here](https://github.com/particle-iot/particle-usb/pull/89/files#diff-d8931074aeb61bc0b98e416152025a1762ef1c8a02a88e194a4c9fe7af695929R665).

2023-08-01 11:58 UTC, sergeuz commented on src/usb-device-node.js
> +				reqData, (err, bytes) => {
It doesn't look like the second callback argument (`bytes`) is defined for OUT transfers: https://github.com/node-usb/node-usb#controltransferbmrequesttype-brequest-wvalue-windex-data_or_length-callbackerror-data

2023-08-01 11:58 UTC, sergeuz commented on src/usb-device-node.js
> +			}
The error handling seems to be copied from the `open()` method but it doesn't make sense in this context. We should just return the error if getting the string descriptor fails.

2023-08-01 11:58 UTC, sergeuz commented on src/usb-device-webusb.js
> +				this._dev.getStringDescriptor(intrface, (err, intrfaceName) => {
The WebUSB API is completely different from the legacy `node-usb` API which is used in `usb-device-node.js` so simply copying the implementation from there won't work.

2023-08-01 11:58 UTC, sergeuz commented on src/wifi-device.test.js
> +		const fakeUSBDevice = { type: 'p2', isInDfuMode: true };
These tests validate the WiFi-specific control requests, why do we want the device to be in DFU mode?

2023-08-01 22:38 UTC, keeramis commented on src/usb-device-node.js
> +				reqData, (err, bytes) => {
The `bytes` was the way to get the number of bytes that were written successfully. This is later returned by the `_sendDnloadRequest` to `doDownload` where the number of bytes returned are consumed to proceed further

https://github.com/particle-iot/particle-usb/pull/89/files#diff-d8931074aeb61bc0b98e416152025a1762ef1c8a02a88e194a4c9fe7af695929R249

2023-08-02 09:05 UTC, keeramis commented on src/usb-device-node.js
> +				reqData, (err, bytes) => {
I am using this as the way to check how many bytes were written. Is there another way to obtain the data size perhaps? Did you mean the data size _sent_ to the `_sendDownloadRequest` method?

2023-08-02 09:10 UTC, sergeuz commented on src/usb-device-node.js
> +				reqData, (err, bytes) => {
We know the data size already, it's `chunkSize`: https://github.com/particle-iot/particle-usb/blob/feature/dfu-impl/src/dfu.js#L245.

2023-08-02 09:12 UTC, keeramis commented on src/usb-device-node.js
> +				reqData, (err, bytes) => {
Ok - understood. Fixed. please check.

2023-08-02 13:00 UTC, keeramis commented on src/dfu.js
> -			// report dfuDNLOAD_IDLE :|
Fixed.

2023-08-02 13:58 UTC, keeramis commented on src/wifi-device.test.js
> +		const fakeUSBDevice = { type: 'p2', isInDfuMode: true };
@sergeuz Corrected this. The new prototype creation checks `isInDfuMode` which checks for `this._info.dfu` where `this` is the device object which contains `_dev`, `_info`, and others. If `_info` is not found, then there is an error in `set-device-prototype` https://github.com/particle-iot/particle-usb/blob/feature/dfu-impl/src/set-device-prototype.js#L56 . So added the `_info` object to the `fakeUSBDevice`.

2023-08-03 13:21 UTC, sergeuz commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
@avtolstoy Do we honor that address? I'm a bit worried we might instruct the bootloader to jump to some random address, e.g. after writing to the DCT:
```
await dev.flashWithDfu(...); // Sets the address and writes to DCT
await dev.reset(); // Sends the leave command
```

2023-08-03 13:24 UTC, keeramis commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
This is again under the control of the CLI. We need not use the ` leave : true ` option and then it will not look into this logic block.

2023-08-03 13:30 UTC, keeramis commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
For this leave() command, we are not sending that dfuSeCommand to the device.
This is the `leave` function that gets called with `reset` ?
https://github.com/particle-iot/particle-usb/blob/feature/dfu-impl/src/dfu.js#L191-L202

2023-08-03 13:33 UTC, sergeuz commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
The set address command is also sent prior to writing each data block. From the spec you linked to:
```
The address pointer can also be set through the last Write memory operation: if a download
operation is performed, the address pointer used for this download is stored and used later
for the jump.
```

2023-08-03 13:58 UTC, avtolstoy commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
@keeramis @sergeuz That `SET_ADDRESS` call should not be necessary here. Yes, by spec it's necessary for STM32 ROM bootloader, and that `SET_ADDRESS` may be used for boot jump, but we don't use that, our jump address is fixed and for things like DCT or external flash does not make sense.

Current `leave()` also handles getting into the correct state (dnload_idle or idle) clearing the error etc on the device side, so I would leave this up to `leave()` entirely and not overcomplicate this method. If we want to reset - `leave()` MUST be able to perform that no matter the state of the DFU state machine on the device side.

2023-08-03 14:02 UTC, keeramis commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
I will get rid of this line then
```
await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
```

2023-08-03 14:03 UTC, avtolstoy commented on src/dfu.js
> +				await this._dfuseCommand(DfuseCommand.DFUSE_COMMAND_SET_ADDRESS_POINTER, startAddress, 4);
`await this._goIntoDfuIdleOrDfuDnloadIdle();` too

2023-08-04 19:09 UTC, sergeuz requested changes

2023-08-04 19:09 UTC, sergeuz commented on src/dfu.js
> +	DEVICE_TO_HOST_STANDARD: 0x80 // Direction: device-to-host; type: standard; recipient: device
This is a bit confusing as this request type has nothing to do with DFU requests for which, as the name suggests, this enum object is defined. Consider either renaming the enum to just `BmRequestType` and the existing constants to e.g. `HOST_TO_DEVICE_CLASS` and `DEVICE_TO_HOST_CLASS`, or using `0x80` as a literal as it was in the original code.

2023-08-06 18:44 UTC, keeramis commented on src/dfu.js
> +	async _sendDnloadRequest(req, wValue) {
The workaround for this is with in the `transferOut` method in the `usb-device-node.js` so node usb was never impacted. This is what it looks like for nodeusb.
https://github.com/particle-iot/particle-usb/blob/feature/dfu-impl/src/usb-device-node.js#L95-L103
```
	transferOut(setup, data) {
		return new Promise((resolve, reject) => {
			if (!data) {
				// NOTE: this is a quirk of some USB device-side implementations
				// where zero-length (no data stage) OUT control requests are not
				// completed and cause a timeout.
				// The workaround is always including a data stage.
				if (!this._quirks.controlOutTransfersRequireDataStage) {
					data = Buffer.alloc(0);
				} else {
					data = Buffer.alloc(1);
				}
			}
```

I can add a dummy buffer in the caller itself but I will leave the workaround in the `usb-device-node.js` as the caller may not always know that there needs to be a dummy data block. Similar workaround is in place for webusb.
https://github.com/particle-iot/particle-usb/blob/feature/dfu-impl/src/usb-device-webusb.js#L86-L88 
```
			if (!data && this._quirks.controlOutTransfersRequireDataStage) {
				data = Buffer.alloc(1);
			}
```
Did you add a dummy block in the caller to resolve it in webusb during your testing?

2023-08-06 19:40 UTC, keeramis commented on src/dfu.js
> +				if (triesLeft === 0 || error.message !== 'LIBUSB_TRANSFER_STALL') {
thanks for the pointers, @sergeuz

2023-08-07 09:22 UTC, sergeuz commented on src/dfu.js
> +		await this._sendDnloadRequest(Buffer.alloc(0), 2);
> Buffer.alloc(0)

This will prevent the `controlOutTransfersRequireDataStage` quirk from working. You need to pass `undefined` instead of a buffer or better make `data` the last argument of `_sendDnloadRequest` so that it can be omitted by the caller if no data stage is required.

2023-08-07 09:22 UTC, sergeuz commented on src/usb-device-webusb.js
> +					throw new UsbStallError(`Status: ${res.status}`);
Note the outer catch block that will wrap this error in `UsbError` and prevent the caller from handling it. Let's rework the error handling as follows:
```js
let res;
try {
	res = await this._dev.controlTransferIn(...);
} catch (err) {
	throw new UsbError('IN control transfer failed', { cause: err });
}
if (res.status !== 'ok') {
	if (res.status === 'stall') {
		throw new UsbStallError('Transfer stalled');
	}
	throw new Error(`Status: ${res.status}`);
}
return Buffer.from(res.data.buffer);
```

Same in `transferOut()`.

2023-08-07 09:25 UTC, sergeuz commented on src/dfu.js
> +	async _sendDnloadRequest(req, wValue) {
> Did you add a dummy block in the caller to resolve it in webusb during your testing?

I didn't debug it at the time but I can confirm that it's fixed now.

@avtolstoy When leaving DFU mode on a platform affected by the missing data stage quirk, wouldn't sending a non-empty data stage in a `DNLOAD` command cause the device to actually write some unwanted data to flash?

2023-08-07 09:31 UTC, sergeuz commented on src/dfu.js
> +		await this._sendDnloadRequest(Buffer.alloc(0), 2);
I'm wrong, actually. It looks like the data stage quirk was introduced for regular control requests, the leave command is not affected. Disregard the comment.

2023-08-07 09:44 UTC, sergeuz commented on test/support/fake-usb.js
> +			setup.bmRequestType !== 0x80) {
This class implements the Particle's control request protocol, it doesn't need to handle `GET_DESCRIPTOR` requests.

2023-08-07 09:44 UTC, sergeuz commented on test/support/fake-usb.js
> +	async _pollUntil(statePredicate) {
Unused method.

2023-08-07 09:44 UTC, sergeuz commented on test/support/fake-usb.js
> +				const sample = [9,2,36,0,1,1,4,192,50,9,4,0,0,0,254,1,2,5,9,4,0,1,0,254,1,2,6,9,33,11,255,0,0,16,26,1];
This looks like a config descriptor but the library can also send this request to get a string descriptor (see `_getStringDescriptor`).

2023-08-07 10:51 UTC, avtolstoy commented on src/dfu.js
>  		bStatusWithPollTimeout &= ~(0xff);
Yup. Needs to be shifted 8 bits:
```
struct DfuGetStatus {
  uint8_t bStatus;
  uint8_t bwPollTimeout[3];
  uint8_t bState;
  uint8_t iString;
};
```

After `readUInt32LE` `bStatus` is in lower byte so can be masked to get, but the rest needs to be `>> 8`

2023-08-07 12:25 UTC, sergeuz commented on test/support/fake-usb.js
> +				const sample = [9,2,36,0,1,1,4,192,50,9,4,0,0,0,254,1,2,5,9,4,0,1,0,254,1,2,6,9,33,11,255,0,0,16,26,1];
Fixed in https://github.com/particle-iot/particle-usb/pull/89/commits/1e4ee1acc6f6178261b30cc289673d6c2570b102.

2023-08-07 12:29 UTC, sergeuz commented on src/wifi-device.test.js
> +		const fakeUSBDevice = { type: 'p2', isInDfuMode: true };
I added a TODO to address creation of devices in tests later. The usual trick with `proxyquire` which is used in other tests doesn't work due to some caching issues.

2023-08-07 12:37 UTC, sergeuz commented on test/support/fake-usb.js
> +	async _pollUntil(statePredicate) {
Fixed in https://github.com/particle-iot/particle-usb/pull/89/commits/1e4ee1acc6f6178261b30cc289673d6c2570b102.

2023-08-07 12:37 UTC, sergeuz commented on test/support/fake-usb.js
> +			setup.bmRequestType !== 0x80) {
Fixed in https://github.com/particle-iot/particle-usb/pull/89/commits/1e4ee1acc6f6178261b30cc289673d6c2570b102.

2023-08-08 22:11 UTC, sergeuz approved these changes
I tested this PR in a Node app and browser and it works as expected. There's no unit tests validating the primary functionality but we agreed to add those later as to not to block other development that needs this feature.

2023-08-14 15:27 UTC, merged