Add error code for protected devices
particle-iot/particle-usb pull request #97
Opened 2024-01-11 15:28 UTC by keeramis

2024-01-17 20:48 UTC, monkbroc requested changes

2024-01-17 20:48 UTC, monkbroc commented on src/device.js
> +			throw new errorForRequest(rep.result);
Don't use new with function calls

2024-01-17 20:48 UTC, monkbroc commented on src/dfu.js
> +			throw new Error('Segment is not erasable');
Use DeviceProtectionError here and in doUpload below

2024-01-17 20:50 UTC, monkbroc commented on src/result.js
> +function errorForRequest(result) {
FYI Andrey, I discussed with Keerthy that for consistency we'd use the DeviceProtectionError for both DFU and control requets so tools like the CLI only have one error to watch out.

2024-01-17 22:59 UTC, monkbroc commented on src/dfu.js
>  		}
Can you check what happens when this function is called with `startAddr: null`? Will it crash?

My thought is that it just doesn't make sense to support calling `doUpload` without a start address and it would be best to remove this `if`

2024-01-17 23:57 UTC, keeramis commented on src/dfu.js
>  		}
Did you mean `segment` is null?

If the `startAddr` is null, then it will simply get the segment from that address and gets the data of `maxSize` bytes from that address. On my Boron, all the bytes read 0xff

If the `segment` is null, it continues anyway with a warning - segment is not referenced in the function after the warning.

Either way, it does not crash.

2024-01-18 00:02 UTC, keeramis commented on src/dfu.js
>  		}
Other than showing a warnings there which is perhaps used in some cases that I am not aware of, the `if` condition can be removed.

2024-01-18 18:24 UTC, monkbroc commented on src/dfu.js
>  		}
I think it's best to have `doUpload` require `startAddr`. It feels weird to support uploading without specifiying a source.
I removed the test for doUpload with startAddr null since we don't want to support this use case anymore.

2024-01-19 21:47 UTC, merged